name: Günlük Uzay Bilgisi Üretici

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Botu Çalıştır
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Metni Depoya Kaydet
        run: |
          git config --global user.name "Uzay Botu"
          git config --global user.email "bot@github.com"
          git add gunluk_uzay.txt
          git commit -m "Günlük uzay bilgisi güncellendi" || exit 0
          git push
          
